set(sources ${sources}
	include/F4SE/API.cpp
	include/F4SE/Interfaces.cpp
	include/F4SE/Logger.cpp
	include/F4SE/Trampoline.cpp
	include/F4SE/Impl/PCH.cpp
	include/F4SE/Impl/WinAPI.cpp
	include/RE/Fallout.cpp
	include/RE/Bethesda/Atomic.cpp
	include/RE/Bethesda/BSExtraData.cpp
	include/RE/Bethesda/BSFixedString.cpp
	include/RE/Bethesda/BSLock.cpp
	include/RE/Bethesda/BSPointerHandle.cpp
	include/RE/Bethesda/BSScaleformManager.cpp
	include/RE/Bethesda/BSScript.cpp
	include/RE/Bethesda/BSSpring.cpp
	include/RE/Bethesda/BSTArray.cpp
	include/RE/Bethesda/Calendar.cpp
	include/RE/Bethesda/CRC.cpp
	include/RE/Bethesda/FormComponents.cpp
	include/RE/Bethesda/InputEvent.cpp
	include/RE/Bethesda/Settings.cpp
	include/RE/Bethesda/TESObjectREFRs.cpp
	include/RE/NetImmerse/NiAVObject.cpp
	include/RE/NetImmerse/NiObjectNET.cpp
	include/RE/NetImmerse/NiRect.cpp
	include/RE/Scaleform/GFx/GFx_Player.cpp
	include/REL/Relocation.cpp
)
