set(SOURCES
	src/PCH.h
	src/Papyrus/Actor.h
	src/Papyrus/ActorBase.h
	src/Papyrus/Armor.h
	src/Papyrus/ArmorAddon.h
	src/Papyrus/Cell.h
	src/Papyrus/Common.h
	src/Papyrus/Component.h
	src/Papyrus/ConstructibleObject.h
	src/Papyrus/DefaultObject.h
	src/Papyrus/EncounterZone.h
	src/Papyrus/EquipSlot.h
	src/Papyrus/F4SE.h
	src/Papyrus/Form.h
	src/Papyrus/Game.h
	src/Papyrus/HeadPart.h
	src/Papyrus/Input.h
	src/Papyrus/InstanceData.h
	src/Papyrus/Location.h
	src/Papyrus/MatSwap.h
	src/Papyrus/Math.h
	src/Papyrus/MiscObject.h
	src/Papyrus/ObjectMod.h
	src/Papyrus/ObjectReference.h
	src/Papyrus/Papyrus.cpp
	src/Papyrus/Papyrus.h
	src/Papyrus/Perk.h
	src/Papyrus/ScriptObject.h
	src/Papyrus/UI.h
	src/Papyrus/Utility.h
	src/Papyrus/WaterType.h
	src/Papyrus/Weapon.h
	src/main.cpp
)
